#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VisualizationSystem.Resource", IsApplication=true)]

namespace VisualizationSystem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Configuration.Resource.String.ApplicationName = global::VisualizationSystem.Resource.String.ApplicationName;
			global::Configuration.Resource.String.Hello = global::VisualizationSystem.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int autorize_button = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int autorizedText = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int log_in_button = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int login = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int password = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int reg_button = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int rep_password = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int sign_up_button = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int unautorize_button = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Autorization = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Autorized = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Registration = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
